### ISSUE TITLE
关于新增返回自增长主键

### ISSUE THREAD

**Issue by ooocici** [pingapi/crabc#9]
如何实现新增数据成功，返回自增长主键信息？

**Comment by pingapi** [comment]
使用注解 @Options(useGeneratedKeys = true,keyProperty = "xx"）
可以拿到自增的主键，xx为自增的主键，把返回的修改条数改为返回自增主键
比如：
<img width="639" alt="image" src="https://github.com/pingapi/crabc-api/assets/50392316/4ccbb98c-de5f-4609-b550-4d1fa0e154ab">

**Comment by ooocici** [comment]
谢谢
